apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssp-pv-rmxml
  labels:
    type: local_app_rmxml
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/ssp_deploy/storage/apps/rmxMl"

