apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssp-pv-python
  labels:
    type: local_app_python
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/ssp_deploy/storage/apps/python"

