apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssp-pv-react
  labels:
    type: local_app_react
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/ssp_deploy/storage/apps/react-ui"

