apiVersion: v1
kind: PersistentVolume
metadata:
  name: java-pv
  labels:
    type: local_java_app
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/javasample"

