apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rmxml-pv-claim
  namespace: {{ .Release.Namespace }}
  labels:
    app: rmxml_pvc_app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.global.sharedVolumeSpringConfiguration.properties.storageSize }}
  storageClassName: manual
  selector:
    matchLabels:
      type: local_app_rmxml
