apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: java-pv-claim
  namespace: {{ .Release.Namespace }}
  labels:
    app: java_pvc_app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.global.sharedVolumeSpringConfiguration.properties.storageSize }}
  storageClassName: manual
  selector:
    matchLabels:
      type: local_java_app
