kind: Service
apiVersion: v1
metadata:
  name: tomcat-service
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort      
  selector:
    server: tomcat
  ports:
  - protocol: TCP
    port: {{ .Values.tomcat.port }}
    targetPort: {{ .Values.tomcat.port }}
    nodePort: 30007
    name: {{ .Values.tomcat.image }} 
  - protocol: TCP
    port: 1025
    targetPort: 1025
    nodePort: 30006
    name: app-port 

