apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-server
  namespace: {{ .Release.Namespace }}
  labels:
    server: tomcat
spec:
  selector:
    matchLabels:
      server: tomcat
      tier: server
  strategy:
    type: {{ .Values.tomcat.strategy }}
  template:
    metadata:
      labels:
        server: tomcat
        tier: server
    spec:
      containers:
      - image: {{ .Values.tomcat.image }}:{{ .Values.tomcat.imageTag }}
        name: {{ .Values.tomcat.image }}
        resources:
           requests:
             cpu: 500m
             memory: 1Gi
           limits:
             cpu: 1
             memory: 3Gi
        ports:
        - containerPort: {{ .Values.tomcat.port }}
          name: {{ .Values.tomcat.image }}
        volumeMounts:
        - name: tomcat-persistent-storage
          mountPath: /usr/local/tomcat/webapps
        - name: tomcat-configuration
          mountPath: /usr/local/tomcat/conf/tomcat-users.xml
          subPath: tomcat-users.xml
      volumes:
      - name: tomcat-persistent-storage
        persistentVolumeClaim:
          claimName: tomcat-pv-claim
      - name: tomcat-configuration
        configMap:
          name: tomcat-configuration
      imagePullSecrets:
      - name: regcred
