apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tomcat-pv-claim
  namespace: {{ .Release.Namespace }}
  labels:
    app: tomcat_pvc_app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.global.sharedVolumeWLPConfiguration.properties.storageSize }}
  storageClassName: manual
  selector:
    matchLabels:
      type: local_app
