apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: react-pv-claim
  namespace: {{ .Release.Namespace }}
  labels:
    app: react_pvc_app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.global.sharedVolumeSpringConfiguration.properties.storageSize }}
  storageClassName: manual
  selector:
    matchLabels:
      type: local_app_react
