apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssp-pv-springboot-config
  labels:
    type: local_springboot_config
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/srinivas/mydata/containerstore/ssp_data/spring_boot"

