apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssp-pv-app
  labels:
    type: local_app
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/srinivas/mydata/containerstore/ssp_data/app"

