apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-backend
  namespace: {{ .Release.Namespace }}
  labels:
    db: mysql
spec:
  selector:
    matchLabels:
      db: mysql
      tier: backend
  strategy:
    type: {{ .Values.mysql.strategy }}
  template:
    metadata:
      labels:
        db: mysql
        tier: backend
    spec:
      containers:
      - image: {{ .Values.mysql.image }}:{{ .Values.mysql.imageTag }}
        name: {{ .Values.mysql.image }}
        resources:
           requests:
             cpu: 500m
             memory: 1Gi
           limits:
             cpu: 1
             memory: 3Gi
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credential
              key: password
        ports:
        - containerPort: {{ .Values.mysql.port }}
          name: {{ .Values.mysql.image }}
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      imagePullSecrets:
      - name: regcred
