apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-server
  namespace: {{ .Release.Namespace }}
  labels:
    server: oauth
spec:
  selector:
    matchLabels:
      server: oauth
      tier: server
  strategy:
    type: {{ .Values.springboot.strategy }}
  template:
    metadata:
      labels:
        server: oauth
        tier: server
    spec:
      containers:
      - image: {{ .Values.springboot.image }}:{{ .Values.springboot.imageTag }}
        name: {{ .Values.springboot.image }}
        resources:
           requests:
             cpu: 500m
             memory: 1Gi
           limits:
             cpu: 1
             memory: 3Gi
        env:
        - name: SPRING_BOOT_MAIN_JAR
          value: {{ .Values.springboot.mainjar }}
        - name: SPRING_BOOT_APP_HOME
          value: {{ .Values.springboot.apphome }}
        ports:
        - containerPort: {{ .Values.springboot.port }}
          name: {{ .Values.springboot.image }}
        volumeMounts:
        - name: oauth-persistent-storage
          mountPath: /usr/app
      volumes:
      - name: oauth-persistent-storage
        persistentVolumeClaim:
          claimName: oauth-pv-claim
      imagePullSecrets:
      - name: regcred
