apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: {{ .Release.Namespace }}
  labels:
    app: mysql_pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.global.sharedVolumeConfiguration.properties.storageSize }}
  storageClassName: manual
  selector:
    matchLabels:
      type: local_db_data
